reports = {
    'results/pw_ba_1.json',
    'results/pw_na_1.json',
    'results/pw_sa_1.json',
    'results/lm_ba_1.json',
    'results/lm_na_1.json',
    'results/lm_sa_1.json',
    'results/hm_ba_1.json',
    'results/hm_na_1.json',
    'results/hm_sa_1.json',
    'results/pw_ba_2.json',
    'results/pw_na_2.json',
    'results/pw_sa_2.json',
    'results/lm_ba_2.json',
    'results/lm_na_2.json',
    'results/lm_sa_2.json',
    'results/hm_ba_2.json',
    'results/hm_na_2.json',
    'results/hm_sa_2.json',
}

reportsRS = {
    'results/_Taloc.json',
    'results/_Mother_Early.json',
    'results/_Mother_Late.json',
    'results/_FetidDevourer.json',
    'results/_Zekvoz.json',
    'results/_Vectis.json',
    'results/_Zul.json',
    # 'results/_Mythrax.json',
    'results/_Ghuun.json',
}
